---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
      server {

        listen {{ .Values.frontendPort }};

        location / {
           root   /usr/share/nginx/html;
           index  index.html;
           try_files $uri $uri/ /index.html;
        }

        location ~ ^/(categories|products|auth|metrics|orders)/ {
            proxy_pass http://{{ .Values.proxy.host }}:{{ .Values.proxy.port }};
        }
      }
